### ISSUE TITLE
Save profile names capitalized at sign-in, mentee, and mentor applications

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-backend#160]
**Description:**
Ensure profile names are saved with the first letter of each word capitalized during sign-in, mentee, and mentor applications.

**Tasks:**
- [ ] Capitalize profile names before saving during sign-in.
- [ ] Capitalize profile names before saving during mentee application.
- [ ] Capitalize profile names before saving during mentor application.
- [ ] Update relevant documentation.

**Acceptance Criteria:**
- Profile names are saved with the first letter of each word capitalized.
- Unit tests confirm proper capitalization.
- No negative impact on existing workflows.

**Additional Information:**

**Related Dependencies or References:**

**Comment by Disura-Randunu** [comment]
Hey @anjula-sack. Shall I work on this issue?

**Comment by Madhawa97** [comment]
Sure go ahead! @Disura-Randunu

**Comment by Disura-Randunu** [comment]
@Madhawa97 Where can I find the documentation that needs to be updated?

**Comment by Disura-Randunu** [comment]
Unit test for registration is failing because "profile" is null.

auth.service.ts : 44 - 48
`
    await profileRepository.save(newProfile)

    const savedProfile = await profileRepository.findOne({
      where: { primary_email: email }
    })

`

Might be becuase it takes some time for the DB to commit and "savedProfile" is empty at that time. Shall I change it as below?

`
    const savedProfile = await profileRepository.save(newProfile)

`

**Comment by anjula-sack** [comment]
@Disura-Randunu Can you send the PR, then let's see what's happening based on your changes

**Comment by Disura-Randunu** [comment]
@anjula-sack added PR: https://github.com/sef-global/scholarx-backend/pull/167
